config/routes.rb
Danhoerr2::Application.routes.draw do
  resources :categories

  resources :users
  resources :portfolios
  resources :task_types
  resources :tasks
  resources :sessions

  get "home/index"
  root :to => "home#index"

  get "planechase/update" => "planechase#update_database"
  get "planechase"  => "planechase#index"
  get "planechase/random" => 'planechase#random', :as => :random

 get "login" => "home#login"
 get "logout" => "sessions#destroy"

 

end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  attr_accessible :project_name, :tasks, :image, :image_cache, :link, :public

  mount_uploader :image, PortfolioUploader

  validates :project_name, :presence => true
  validates :tasks, :presence => true
  validates :image, :presence => true
  validates :link, :presence => true
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_filter :authorize, :only => [:index, :show, :new, :edit, :create, :update, :destroy]
  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @portfolios }
    end
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
    @portfolio = Portfolio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @portfolio }
    end
  end

  # GET /portfolios/new
  # GET /portfolios/new.json
  def new
    @portfolio = Portfolio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @portfolio }
    end
  end

  # GET /portfolios/1/edit
  def edit
    @portfolio = Portfolio.find(params[:id])
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(params[:portfolio])

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, :notice => 'Portfolio was successfully created.' }
        format.json { render :json => @portfolio, :status => :created, :location => @portfolio }
      else
        format.html { render :action => "new" }
        format.json { render :json => @portfolio.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /portfolios/1
  # PUT /portfolios/1.json
  def update
    @portfolio = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio.update_attributes(params[:portfolio])
        format.html { redirect_to @portfolio, :notice => 'Portfolio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @portfolio.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio = Portfolio.find(params[:id])
    @portfolio.destroy

    respond_to do |format|
      format.html { redirect_to portfolios_url }
      format.json { head :no_content }
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for @portfolio, :html => {:multipart => true} do |f| %>
  <% if @portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% @portfolio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_name %><br />
    <%= f.text_field :project_name %>
  </div>
  <div class="field">
    <%= f.label :tasks %><br />
    <%= f.text_area :tasks %>
  </div>
    <div class="field">
    <%= f.label :public %><br />
    <%= f.select :public, %w(true false) %>
  </div>

  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <br />
  <%= image_tag(@portfolio.image_url) if @portfolio.image? %>
  <br /><br />
  <div class="field">
    <%= f.label :image%>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<div class="wrapper">
<h1>Editing portfolio</h1>

<%= render 'form' %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>
</div>

app/views/portfolios/index.html.erb
<div class="wrapper">
<h1>Listing portfolios</h1>
<%= link_to 'New Portfolio', new_portfolio_path %>
<table>
  <tr>
    <th>Project name</th>
    <th>Tasks</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @portfolios.each do |portfolio| %>
  <tr>
    <td><%= portfolio.project_name %></td>
    <td><%= portfolio.tasks %></td>
    <td><%= image_tag portfolio.image_url(:thumb) if portfolio.image? %></td>
    <td><%= link_to 'Show', portfolio %></td>
    <td><%= link_to 'Edit', edit_portfolio_path(portfolio) %></td>
    <td><%= link_to 'Destroy', portfolio, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Portfolio', new_portfolio_path %>
</div>

app/views/portfolios/new.html.erb
<div class="wrapper">
<h1>New portfolio</h1>

<%= render 'form' %>

<%= link_to 'Back', portfolios_path %>
</div>

app/views/portfolios/show.html.erb
<div class="wrapper">
<p id="notice"><%= notice %></p>

<p>
  <b>Project name:</b>
  <%= @portfolio.project_name %>
</p>

<p>
  <b>Tasks:</b>
  <%= @portfolio.tasks %>
</p>

<p>
  <b>Public:</b>
  <%= @portfolio.public %>
</p>



<%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |
<%= link_to 'Back', portfolios_path %>
</div>