config/routes.rb
Danhoerr2::Application.routes.draw do
  resources :categories

  resources :users
  resources :portfolios
  resources :task_types
  resources :tasks
  resources :sessions

  get "home/index"
  root :to => "home#index"

  get "planechase/update" => "planechase#update_database"
  get "planechase"  => "planechase#index"
  get "planechase/random" => 'planechase#random', :as => :random

 get "login" => "home#login"
 get "logout" => "sessions#destroy"

 

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@tasks = Task.all
  	@categories = Category.all
  	@portfolios = Portfolio.all
  	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tasks }
    end
  end

  def login
    respond_to do |format|
      format.html
    end
  end
end

app/views/home/index.html.erb
<header>
    <div class="wrapper">
    	<h1>Hi, I'm <a href="/resume.json">Dan!</a></h1>
    	<p>I'm a web developer for <a href="http://appdirect.com">AppDirect</a>'s <a href="http://info.appdirect.com/d+c">Design+Communications</a> department with hobbies ranging from homebrewing beer to playing all manner of games. I don't like shrimp unless they're drowning in butter, but I love me a crab pickin'. One of my strongest passions is for learning new things.  </p>
  	</div>
</header>
<div role="main">
	<div class="wrapper">
		<% @categories.each_with_index do |category, index| %>
			<div class="col<%= index+1 %> <%= category.class %>">
			<h2><%=raw category.name %></h2>
				<ul>
					<% @tasks.each do |task| %>
						<% if task.category_id.to_i == category.id %>
							<li><%= task.name %></li>
						<% end %>
					<% end %>
				</ul>
			</div>
		<% end %>
	</div>
</div>
    <div class="sites">
       <div class="wrapper">
        <h2>Some sites I've had the pleasure to work on:</h2>
        <ul class="portfolio">
          <% @portfolios.each do |portfolio| %>
            <% next if portfolio.public == false && session[:user_role].nil? %>
          <li>
            <%= link_to(image_tag(portfolio.image), portfolio.link) %>
            <p class="details jshide"><%= portfolio.tasks %></p>
          </li>
          <% end %>
        </ul>
      </div><!-- end wrapper -->
    </div><!-- end sites -->

app/views/home/login.html.erb
<div class="wrapper">
  <h1>Hello, please login</h1>
  <%= form_tag sessions_path do %>
    <div class="field">
      <%= label_tag :email %>
      <%= text_field_tag :email, params[:email] %>
    </div>
    <div class="field">
      <%= label_tag :password %>
      <%= password_field_tag :password %>
    </div>
    <div class="actions">
      <%= submit_tag "Log in", class: "btn" %>
    </div>
  <% end %>
</div>